all:
	go install github.com/cmu440/bitcoin/client
	go install github.com/cmu440/bitcoin/miner
	go install github.com/cmu440/bitcoin/server
	go install github.com/cmu440/bitcoin/ctest
	go install github.com/cmu440/bitcoin/mtest
	go install github.com/cmu440/bitcoin/stest
